sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t joseluisjb1990/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true joseluisjb1990/docker-react npm run test