sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t joseluisjb1990/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true joseluisjb1990/docker-react npm run test

deploy:
  provider : elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-370955926339"
  bucket_path: "docker-react"
  
  access_key_id: 
    secure: $AWS_ACCESS_KEY_ID
  
  secret_access_key:
    secure: $AWS_SECRET_KEY
  
  on:
    branch: master